-- Bank of mock-interview questions, either generated by the Claude API (see
-- MockInterviewQuestionService) and persisted for reuse, or added directly by an admin (see
-- AdminMockInterviewQuestionService). skills mirrors candidate_profiles.skills' text[] treatment
-- (see V-of-that-table / CandidateProfile) rather than a join table, since a skill here is just a
-- label, not a foreign entity. A question is tagged with whichever skills/industry/experience
-- level were selected for the session that generated it (AI) or whatever an admin assigns
-- (ADMIN) — see MockInterviewQuestionService.getSessionQuestions for how these tags are matched
-- against a candidate's session.
create table mock_interview_questions (
    id uuid primary key default gen_random_uuid(),
    text text not null,
    category varchar(255) not null,
    skills text[] not null default '{}',
    industry varchar(255),
    experience_level varchar(20)
        check (experience_level in ('ENTRY_LEVEL', 'MID_LEVEL', 'SENIOR', 'LEADERSHIP')),
    important boolean not null default false,
    source varchar(20) not null check (source in ('AI', 'ADMIN')),
    created_at timestamptz not null default now()
);

create index idx_mock_interview_questions_category on mock_interview_questions (category);
-- Speeds up the skill-overlap filter in MockInterviewQuestionService.matchingQuestions.
create index idx_mock_interview_questions_skills on mock_interview_questions using gin (skills);
