package com.openopportunity.mockinterview;

import com.openopportunity.job.ExperienceLevel;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/** A bank entry a mock-interview session question can be pulled from — either persisted after
 * being generated by Claude (source AI, tagged with the skills/industry/experience level the
 * session that generated it used) or added directly by an admin (source ADMIN). See
 * MockInterviewQuestionService.getSessionQuestions for how the bank is queried and topped up. */
@Entity
@Table(name = "mock_interview_questions")
public class MockInterviewQuestion {

    @Id
    @Column(updatable = false, nullable = false)
    private UUID id;

    @Column(nullable = false, columnDefinition = "text")
    private String text;

    @Column(nullable = false, length = 255)
    private String category;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(nullable = false, columnDefinition = "text[]")
    private List<String> skills;

    @Column(length = 255)
    private String industry;

    @Enumerated(EnumType.STRING)
    @Column(name = "experience_level", length = 20)
    private ExperienceLevel experienceLevel;

    @Column(nullable = false)
    private boolean important;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20, updatable = false)
    private QuestionSource source;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected MockInterviewQuestion() {
        // JPA
    }

    public MockInterviewQuestion(
            String text,
            String category,
            List<String> skills,
            String industry,
            ExperienceLevel experienceLevel,
            QuestionSource source) {
        this.id = UUID.randomUUID();
        this.text = text;
        this.category = category;
        this.skills = skills;
        this.industry = industry;
        this.experienceLevel = experienceLevel;
        this.important = false;
        this.source = source;
    }

    @PrePersist
    void onCreate() {
        createdAt = Instant.now();
    }

    public void setImportant(boolean important) {
        this.important = important;
    }

    public UUID getId() {
        return id;
    }

    public String getText() {
        return text;
    }

    public String getCategory() {
        return category;
    }

    public List<String> getSkills() {
        return skills;
    }

    public String getIndustry() {
        return industry;
    }

    public ExperienceLevel getExperienceLevel() {
        return experienceLevel;
    }

    public boolean isImportant() {
        return important;
    }

    public QuestionSource getSource() {
        return source;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
