package com.openopportunity.mockinterview;

import com.openopportunity.job.ExperienceLevel;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/** A bank entry a mock-interview session question can be pulled from — either persisted after
 * being generated by Claude (source AI, tagged with the skills/industry/experience level(s) the
 * session that generated it used) or added directly by an admin (source ADMIN). See
 * MockInterviewQuestionService.getSessionQuestions for how the bank is queried and topped up. */
@Entity
@Table(name = "mock_interview_questions")
public class MockInterviewQuestion {

    @Id
    @Column(updatable = false, nullable = false)
    private UUID id;

    @Column(nullable = false, columnDefinition = "text")
    private String text;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(nullable = false, columnDefinition = "text[]")
    private List<String> skills;

    @Column(length = 255)
    private String industry;

    // Stored as text[] of enum names rather than List<ExperienceLevel> directly — mirrors the
    // proven `skills` column above rather than relying on Hibernate's array-of-enum mapping,
    // which this codebase has no existing precedent for. getExperienceLevels()/the constructor
    // convert at the Java API boundary so callers still work with ExperienceLevel, not raw
    // strings. Empty means "any experience level" — same wildcard convention the null
    // single-value column used before it (see V62), just expressed as an empty array.
    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "experience_levels", nullable = false, columnDefinition = "text[]")
    private List<String> experienceLevels;

    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private QuestionDifficulty difficulty;

    @Column(nullable = false)
    private boolean important;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20, updatable = false)
    private QuestionSource source;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected MockInterviewQuestion() {
        // JPA
    }

    public MockInterviewQuestion(
            String text,
            List<String> skills,
            String industry,
            List<ExperienceLevel> experienceLevels,
            QuestionDifficulty difficulty,
            QuestionSource source) {
        this.id = UUID.randomUUID();
        this.text = text;
        this.skills = skills;
        this.industry = industry;
        this.experienceLevels =
                experienceLevels.stream().map(ExperienceLevel::name).toList();
        this.difficulty = difficulty;
        this.important = false;
        this.source = source;
    }

    @PrePersist
    void onCreate() {
        createdAt = Instant.now();
    }

    public void setImportant(boolean important) {
        this.important = important;
    }

    public UUID getId() {
        return id;
    }

    public String getText() {
        return text;
    }

    public List<String> getSkills() {
        return skills;
    }

    public String getIndustry() {
        return industry;
    }

    public List<ExperienceLevel> getExperienceLevels() {
        return experienceLevels.stream().map(ExperienceLevel::valueOf).toList();
    }

    public QuestionDifficulty getDifficulty() {
        return difficulty;
    }

    public boolean isImportant() {
        return important;
    }

    public QuestionSource getSource() {
        return source;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
